language: python

dist: xenial
sudo: false

python:
  - "2.7"
  - "3.5"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-software-properties
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install -y python-gdal python3-gdal devscripts

install:
  - pip install click mappyfile pyyaml
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - find . -type f -name "*.py" | xargs flake8

after_success:
  - python setup.py sdist bdist_wheel --universal
  - debuild -b -uc -us
