language: python

dist: xenial
sudo: false

python:
  - "2.7"
#  - "3.5"

virtualenv:
  system_site_packages: true

env:
  - GEOMET_CLIMATE_BASEDIR=$TRAVIS_BUILD_DIR/_build GEOMET_CLIMATE_DATADIR=$TRAVIS_BUILD_DIR/tests/data/climate GEOMET_CLIMATE_CONFIG=$TRAVIS_BUILD_DIR/tests/geomet-climate-test.yml GEOMET_CLIMATE_URL=http://localhost:8099/

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-software-properties
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install -y python-gdal python3-gdal devscripts fakeroot mapserver-bin python-mapscript debhelper python-setuptools

install:
  - pip install click mappyfile pyyaml
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - . tests/geomet-climate-test.env
  - python setup.py test
  - find . -type f -name "*.py" | xargs flake8
  - geomet-climate vrt generate
  - geomet-climate tileindex generate
  - geomet-climate mapfile generate -l en -s WMS
  - geomet-climate mapfile generate -l fr -s WMS
  - geomet-climate mapfile generate -l en -s WCS
  - geomet-climate mapfile generate -l fr -s WCS
  - mapserv -nh QUERY_STRING="map=$GEOMET_CLIMATE_BASEDIR/mapfile/geomet-climate-WMS-en.map&service=WMS&version=1.3.0&request=GetCapabilities" > $GEOMET_CLIMATE_BASEDIR/geomet-climate-WMS-1.3.0-capabilities-en.xml
  - mapserv -nh QUERY_STRING="map=$GEOMET_CLIMATE_BASEDIR/mapfile/geomet-climate-WMS-fr.map&lang=fr&service=WMS&version=1.3.0&request=GetCapabilities" > $GEOMET_CLIMATE_BASEDIR/geomet-climate-WMS-1.3.0-capabilities-fr.xml
  - mapserv -nh QUERY_STRING="map=$GEOMET_CLIMATE_BASEDIR/mapfile/geomet-climate-WCS-en.map&service=WCS&version=2.1.0&request=GetCapabilities" > $GEOMET_CLIMATE_BASEDIR/geomet-climate-WCS-2.0.1-capabilities-en.xml
  - mapserv -nh QUERY_STRING="map=$GEOMET_CLIMATE_BASEDIR/mapfile/geomet-climate-WCS-fr.map&lang=fr&service=WCS&version=2.1.0&request=GetCapabilities" > $GEOMET_CLIMATE_BASEDIR/geomet-climate-WCS-2.0.1-capabilities-fr.xml

after_success:
  - python setup.py cleanbuild
  - python setup.py sdist bdist_wheel --universal
  - debuild -b -uc -us
