language: python

dist: bionic
sudo: false

python:
  - "3.6"

virtualenv:
  system_site_packages: true

env:
    global:
        - DEBIAN_FRONTEND=noninteractive
        - CPLUS_INCLUDE_PATH=/usr/include/gdal
        - C_INCLUDE_PATH=/usr/include/gdal
        - GEOMET_CLIMATE_BASEDIR=$TRAVIS_BUILD_DIR/_build
        - GEOMET_CLIMATE_DATADIR=$TRAVIS_BUILD_DIR/tests/data/climate
        - GEOMET_CLIMATE_CONFIG=$TRAVIS_BUILD_DIR/tests/geomet-climate-test.yml
        - GEOMET_CLIMATE_URL=http://localhost:8099/

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - gdal-bin
      - libgdal-dev
      - libsqlite3-mod-spatialite
      - libproj-dev
      - python3-dev
      - python3-gdal
      - python3-mapscript
      - devscripts
      - fakeroot
      - debhelper
      - python-setuptools 
      - python3-setuptools 
      - python3-all
      - python3-matplotlib

before_install:
  - sudo apt-get install -y mapserver-bin
  - mapserv -v
  - sudo apt-get -qq update
  - sudo apt-get install -y software-properties-common

install:
  - pip install GDAL==`gdalinfo --version | cut -d' ' -f2 | cut -d',' -f1`
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - . tests/geomet-climate-test.env
  - python setup.py test
  - find . -type f -name "*.py" | xargs flake8
  - geomet-climate vrt generate
  - geomet-climate tileindex generate
  - geomet-climate legend generate
  - geomet-climate mapfile generate -s WMS
  - geomet-climate mapfile generate -s WCS
  - mapserv -nh QUERY_STRING="map=$GEOMET_CLIMATE_BASEDIR/mapfile/geomet-climate-WMS-en.map&service=WMS&version=1.3.0&request=GetCapabilities" > $GEOMET_CLIMATE_BASEDIR/geomet-climate-WMS-1.3.0-capabilities-en.xml
  - mapserv -nh QUERY_STRING="map=$GEOMET_CLIMATE_BASEDIR/mapfile/geomet-climate-WMS-fr.map&lang=fr&service=WMS&version=1.3.0&request=GetCapabilities" > $GEOMET_CLIMATE_BASEDIR/geomet-climate-WMS-1.3.0-capabilities-fr.xml
  - mapserv -nh QUERY_STRING="map=$GEOMET_CLIMATE_BASEDIR/mapfile/geomet-climate-WCS-en.map&service=WCS&version=2.1.0&request=GetCapabilities" > $GEOMET_CLIMATE_BASEDIR/geomet-climate-WCS-2.0.1-capabilities-en.xml
  - mapserv -nh QUERY_STRING="map=$GEOMET_CLIMATE_BASEDIR/mapfile/geomet-climate-WCS-fr.map&lang=fr&service=WCS&version=2.1.0&request=GetCapabilities" > $GEOMET_CLIMATE_BASEDIR/geomet-climate-WCS-2.0.1-capabilities-fr.xml

after_success:
  - python setup.py cleanbuild
  - python setup.py sdist bdist_wheel --universal
  - sudo debuild -b -uc -us
